#!/bin/sh
#
# This file is released under the terms of the Artistic License.  Please see
# the file LICENSE, included in this package, for details.
#
# Copyright (C) 2006      Open Source Development Labs, Inc.
#               2006-2014 Mark Wong
#               2014      2ndQuadrant, Ltd.
#

cmd_clear=0

while getopts "c" opt; do
	case $opt in
	c)
		cmd_clear=1
		;;
	\?)
		exit 1
		;;
	esac
done

PSQL="psql -v ON_ERROR_STOP=1 -X -q"

if [ $cmd_clear -eq 1 ]; then
    SQL="DELETE FROM time_statistics"
fi;

$PSQL -c "$SQL;"
exit $?
