#!/bin/sh
#
# This file is released under the terms of the Artistic License.
# Please see the file LICENSE, included in this package, for details.
#
# Copyright (C) 2002-2008 Open Source Development Labs, Inc.
#               2002-2015 Mark Wong
#               2015      2ndQuadrant, Ltd.
#

load_table()
{
	table=$1
	file=${table}.dat

	if [ $CHUNKS -eq 1 ] || [ "$table" = "nation" ] || \
			[ "$table" = "region" ]; then
		$PSQL << __EOF__
COPY $table FROM '$DSS_PATH/$file' USING DELIMITERS '|' NULL '';
__EOF__
	else
		i=1
		while [ $i -le $CHUNKS ]; do
			$PSQL << __EOF__ &
COPY $table FROM '$DSS_PATH/$file.$i' USING DELIMITERS '|' NULL '';
__EOF__
			i=$(( $i + 1 ))
		done
		wait
	fi
}

store_sales()
{
	load_table store_sales

	$PSQL -c "VACUUM ANALYZE store_sales;"

	$PSQL << __EOF__ &
ALTER TABLE store_sales
ADD CONSTRAINT pk_store_sales
PRIMARY KEY (ss_item_sk, ss_ticket_number);
__EOF__
}

store_returns()
{
	load_table store_returns
	$PSQL -c "VACUUM ANALYZE store_returns;"

	$PSQL << __EOF__ &
ALTER TABLE store_returns
ADD CONSTRAINT pk_store_returns
PRIMARY KEY (sr_item_sk, sr_ticket_number);
__EOF__
}

catalog_sales()
{
	load_table catalog_sales
	$PSQL -c "VACUUM ANALYZE catalog_sales;"

	$PSQL << __EOF__ &
ALTER TABLE catalog_sales
ADD CONSTRAINT pk_catalog_sales
PRIMARY KEY (cs_item_sk, cs_order_number);
__EOF__
}

catalog_returns()
{
	load_table catalog_returns
	$PSQL -c "VACUUM ANALYZE catalog_returns;"

	$PSQL << __EOF__ &
ALTER TABLE catalog_returns
ADD CONSTRAINT pk_catalog_returns
PRIMARY KEY (cr_item_sk, cr_order_number);
__EOF__
}

web_sales()
{
	load_table web_sales
	$PSQL -c "VACUUM ANALYZE web_sales;"

	$PSQL << __EOF__ &
ALTER TABLE web_sales
ADD CONSTRAINT pk_web_sales
PRIMARY KEY (ws_item_sk, ws_order_number);
__EOF__
}

web_returns()
{
	load_table web_returns
	$PSQL -c "VACUUM ANALYZE web_returns;"

	$PSQL << __EOF__ &
ALTER TABLE web_returns
ADD CONSTRAINT pk_web_returns
PRIMARY KEY (wr_order_number, wr_item_sk);
__EOF__
}

inventory()
{
	load_table inventory
	$PSQL -c "VACUUM ANALYZE inventory;"

	$PSQL << __EOF__ &
ALTER TABLE inventory
ADD CONSTRAINT pk_inventory
PRIMARY KEY (inv_date_sk, inv_item_sk, inv_warehouse_sk);
__EOF__
}

store()
{
	load_table store
	$PSQL -c "VACUUM ANALYZE store;"

	$PSQL << __EOF__ &
ALTER TABLE store
ADD CONSTRAINT pk_store
PRIMARY KEY (s_store_sk);
__EOF__
}

call_center()
{
	load_table call_center
	$PSQL -c "VACUUM ANALYZE call_center;"

	$PSQL << __EOF__ &
ALTER TABLE call_center
ADD CONSTRAINT pk_call_center
PRIMARY KEY (cc_call_center_sk);
__EOF__
}

catalog_page()
{
	load_table catalog_page
	$PSQL -c "VACUUM ANALYZE catalog_page;"

	$PSQL << __EOF__ &
ALTER TABLE catalog_page
ADD CONSTRAINT pk_catalog_page
PRIMARY KEY (cp_catalog_page_sk);
__EOF__
}

web_site()
{
	load_table web_site
	$PSQL -c "VACUUM ANALYZE web_site;"

	$PSQL << __EOF__ &
ALTER TABLE web_site
ADD CONSTRAINT pk_web_site
PRIMARY KEY (web_site_sk);
__EOF__
}

web_page()
{
	load_table web_page
	$PSQL -c "VACUUM ANALYZE web_page;"

	$PSQL << __EOF__ &
ALTER TABLE web_page
ADD CONSTRAINT pk_web_page
PRIMARY KEY (wp_web_page_sk);
__EOF__
}

warehouse()
{
	load_table warehouse
	$PSQL -c "VACUUM ANALYZE warehouse;"

	$PSQL << __EOF__ &
ALTER TABLE warehouse
ADD CONSTRAINT pk_warehouse
PRIMARY KEY (w_warehouse_sk);
__EOF__
}

customer()
{
	load_table customer
	$PSQL -c "VACUUM ANALYZE customer;"

	$PSQL << __EOF__ &
ALTER TABLE customer
ADD CONSTRAINT pk_customer
PRIMARY KEY (c_customer_sk);
__EOF__
}

customer_address()
{
	load_table customer_address
	$PSQL -c "VACUUM ANALYZE customer_address;"

	$PSQL << __EOF__ &
ALTER TABLE customer_address
ADD CONSTRAINT pk_customer_address
PRIMARY KEY (ca_address_sk);
__EOF__
}

customer_demographics()
{
	load_table customer_demographics
	$PSQL -c "VACUUM ANALYZE customer_demographics;"

	$PSQL << __EOF__ &
ALTER TABLE customer_demographics
ADD CONSTRAINT pk_customer_demographics
PRIMARY KEY (cd_demo_sk);
__EOF__
}

date_dim()
{
	load_table date_dim
	$PSQL -c "VACUUM ANALYZE date_dim;"

	$PSQL << __EOF__ &
ALTER TABLE date_dim
ADD CONSTRAINT pk_date_dim
PRIMARY KEY (d_date_sk);
__EOF__
}

household_demographics()
{
	load_table household_demographics
	$PSQL -c "VACUUM ANALYZE household_demographics;"

	$PSQL << __EOF__ &
ALTER TABLE household_demographics
ADD CONSTRAINT pk_household_demographics
PRIMARY KEY (hd_demo_sk);
__EOF__
}

item()
{
	load_table item
	$PSQL -c "VACUUM ANALYZE item;"

	$PSQL << __EOF__ &
ALTER TABLE item
ADD CONSTRAINT pk_item
PRIMARY KEY (i_item_sk);
__EOF__
}

income_band()
{
	load_table income_band
	$PSQL -c "VACUUM ANALYZE income_band;"

	$PSQL << __EOF__ &
ALTER TABLE income_band
ADD CONSTRAINT pk_income_band
PRIMARY KEY (ib_income_band_sk);
__EOF__
}

promotion()
{
	load_table promotion
	$PSQL -c "VACUUM ANALYZE promotion;"

	$PSQL << __EOF__ &
ALTER TABLE promotion
ADD CONSTRAINT pk_promotion
PRIMARY KEY (p_promo_sk);
__EOF__
}

reason()
{
	load_table reason
	$PSQL -c "VACUUM ANALYZE reason;"

	$PSQL << __EOF__ &
ALTER TABLE reason
ADD CONSTRAINT pk_reason
PRIMARY KEY (r_reason_sk);
__EOF__
}

ship_mode()
{
	load_table ship_mode
	$PSQL -c "VACUUM ANALYZE ship_mode;"

	$PSQL << __EOF__ &
ALTER TABLE ship_mode
ADD CONSTRAINT pk_ship_mode
PRIMARY KEY (sm_ship_mode_sk);
__EOF__
}

time_dim()
{
	load_table time_dim
	$PSQL -c "VACUUM ANALYZE time_dim;"

	$PSQL << __EOF__ &
ALTER TABLE time_dim
ADD CONSTRAINT pk_time_dim
PRIMARY KEY (t_time_sk);
__EOF__
}

dsdgen_version()
{
	load_table dsdgen_version
	$PSQL -c "VACUUM ANALYZE dsdgen_version;"
}

time_statistics()
{
	load_table time_statistics
	$PSQL -c "VACUUM ANALYZE time_statistics;"
}

dataset()
{
	load_table dataset
	$PSQL -c "VACUUM ANALYZE dataset;"
}

CHUNKS=1
USE_TABLESPACES=0
while getopts "C:t" OPT; do
	case $OPT in
	C)
		CHUNKS=$OPTARG
		;;
	t)
		USE_TABLESPACES=1
		;;
	esac
done

PSQL="psql -v ON_ERROR_STOP=1 -X"

store_sales &
store_returns &
catalog_sales &
catalog_returns &
web_sales &
web_returns &
inventory &
store &
call_center &
catalog_page &
web_site &
web_page &
warehouse &
customer &
customer_address &
customer_demographics &
date_dim &
household_demographics &
item &
income_band &
promotion &
reason &
ship_mode &
time_dim &

wait

$PSQL << __EOF__
ALTER TABLE store_sales
ADD CONSTRAINT fk_ss_sold_date_sk FOREIGN KEY (ss_sold_date_sk)
REFERENCES date_dim (d_date_sk);

ALTER TABLE store_sales
ADD CONSTRAINT fk_ss_sold_time_sk FOREIGN KEY (ss_sold_time_sk)
REFERENCES time_dim (t_time_sk);

ALTER TABLE store_sales
ADD CONSTRAINT fk_ss_item_sk FOREIGN KEY (ss_item_sk)
REFERENCES item (i_item_sk);

ALTER TABLE store_sales
ADD CONSTRAINT fk_ss_customer_sk FOREIGN KEY (ss_customer_sk)
REFERENCES customer (c_customer_sk);

ALTER TABLE store_sales
ADD CONSTRAINT fk_ss_cdemo_sk FOREIGN KEY (ss_cdemo_sk)
REFERENCES customer_demographics (cd_demo_sk);

ALTER TABLE store_sales
ADD CONSTRAINT fk_ss_hdemo_sk FOREIGN KEY (ss_hdemo_sk)
REFERENCES household_demographics (hd_demo_sk);

ALTER TABLE store_sales
ADD CONSTRAINT fk_ss_addr_sk FOREIGN KEY (ss_addr_sk)
REFERENCES customer_address (ca_address_sk);

ALTER TABLE store_sales
ADD CONSTRAINT fk_ss_store_sk FOREIGN KEY (ss_store_sk)
REFERENCES store (s_store_sk);

ALTER TABLE store_sales
ADD CONSTRAINT fk_ss_promo_sk FOREIGN KEY (ss_promo_sk)
REFERENCES promotion (p_promo_sk);

ALTER TABLE store_returns
ADD CONSTRAINT fk_sr_returned_date_sk FOREIGN KEY (sr_returned_date_sk)
REFERENCES date_dim (d_date_sk);

ALTER TABLE store_returns
ADD CONSTRAINT fk_sr_return_time_sk FOREIGN KEY (sr_return_time_sk)
REFERENCES time_dim (t_time_sk);

ALTER TABLE store_returns
ADD CONSTRAINT fk_sr_item_sk1 FOREIGN KEY (sr_item_sk)
REFERENCES item (i_item_sk);

ALTER TABLE store_returns
ADD CONSTRAINT fk_sr_item_sk2 FOREIGN KEY (sr_item_sk, sr_ticket_number)
REFERENCES store_sales (ss_item_sk, ss_ticket_number);

ALTER TABLE store_returns
ADD CONSTRAINT fk_sr_customer_sk FOREIGN KEY (sr_customer_sk)
REFERENCES customer (c_customer_sk);

ALTER TABLE store_returns
ADD CONSTRAINT fk_sr_cdemo_sk FOREIGN KEY (sr_cdemo_sk)
REFERENCES customer_demographics (cd_demo_sk);

ALTER TABLE store_returns
ADD CONSTRAINT fk_sr_hdemo_sk FOREIGN KEY (sr_hdemo_sk)
REFERENCES household_demographics (hd_demo_sk);

ALTER TABLE store_returns
ADD CONSTRAINT fk_sr_addr_sk FOREIGN KEY (sr_addr_sk)
REFERENCES customer_address (ca_address_sk);

ALTER TABLE store_returns
ADD CONSTRAINT fk_sr_reason_sk FOREIGN KEY (sr_reason_sk)
REFERENCES reason (r_reason_sk);

ALTER TABLE store_returns
ADD CONSTRAINT fk_sr_store_sk FOREIGN KEY (sr_store_sk)
REFERENCES store (s_store_sk);

ALTER TABLE catalog_sales
ADD CONSTRAINT fk_cs_sold_date_sk FOREIGN KEY (cs_sold_date_sk)
REFERENCES date_dim (d_date_sk);

ALTER TABLE catalog_sales
ADD CONSTRAINT fk_cs_sold_time_sk FOREIGN KEY (cs_sold_time_sk)
REFERENCES time_dim (t_time_sk);

ALTER TABLE catalog_sales
ADD CONSTRAINT fk_cs_ship_date_sk FOREIGN KEY (cs_ship_date_sk)
REFERENCES date_dim (d_date_sk);

ALTER TABLE catalog_sales
ADD CONSTRAINT fk_cs_bill_customer_sk FOREIGN KEY (cs_bill_customer_sk)
REFERENCES customer (c_customer_sk);

ALTER TABLE catalog_sales
ADD CONSTRAINT fk_cs_bill_cdemo_sk FOREIGN KEY (cs_bill_cdemo_sk)
REFERENCES customer_demographics (cd_demo_sk);

ALTER TABLE catalog_sales
ADD CONSTRAINT fk_cs_bill_hdemo_sk FOREIGN KEY (cs_bill_hdemo_sk)
REFERENCES household_demographics (hd_demo_sk);

ALTER TABLE catalog_sales
ADD CONSTRAINT fk_cs_bill_addr_sk FOREIGN KEY (cs_bill_addr_sk)
REFERENCES customer_address (ca_address_sk);

ALTER TABLE catalog_sales
ADD CONSTRAINT fk_cs_call_center_sk FOREIGN KEY (cs_call_center_sk)
REFERENCES call_center (cc_call_center_sk);

ALTER TABLE catalog_sales
ADD CONSTRAINT fk_cs_ship_mode_sk FOREIGN KEY (cs_ship_mode_sk)
REFERENCES ship_mode (sm_ship_mode_sk);

ALTER TABLE catalog_sales
ADD CONSTRAINT fk_cs_warehouse_sk FOREIGN KEY (cs_warehouse_sk)
REFERENCES warehouse (w_warehouse_sk);

ALTER TABLE catalog_sales
ADD CONSTRAINT fk_cs_item_sk FOREIGN KEY (cs_item_sk)
REFERENCES item (i_item_sk);

ALTER TABLE catalog_sales
ADD CONSTRAINT fk_cs_promo_sk FOREIGN KEY (cs_promo_sk)
REFERENCES promotion (p_promo_sk);

ALTER TABLE catalog_returns
ADD CONSTRAINT fk_cr_returned_date_sk FOREIGN KEY (cr_returned_date_sk)
REFERENCES date_dim (d_date_sk);

ALTER TABLE catalog_returns
ADD CONSTRAINT fk_cr_returned_time_sk FOREIGN KEY (cr_returned_time_sk)
REFERENCES time_dim (t_time_sk);

ALTER TABLE catalog_returns
ADD CONSTRAINT fk_cr_item_sk1 FOREIGN KEY (cr_item_sk)
REFERENCES item (i_item_sk);

ALTER TABLE catalog_returns
ADD CONSTRAINT fk_cr_item_sk2 FOREIGN KEY (cr_item_sk, cr_order_number)
REFERENCES catalog_sales (cs_item_sk, cs_order_number);

ALTER TABLE catalog_returns
ADD CONSTRAINT fk_cr_refunded_customer_sk FOREIGN KEY (cr_refunded_customer_sk)
REFERENCES customer (c_customer_sk);

ALTER TABLE catalog_returns
ADD CONSTRAINT fk_cr_refunded_cdemo_sk FOREIGN KEY (cr_refunded_cdemo_sk)
REFERENCES customer_demographics (cd_demo_sk);

ALTER TABLE catalog_returns
ADD CONSTRAINT fk_cr_refunded_hdemo_sk FOREIGN KEY (cr_refunded_hdemo_sk)
REFERENCES household_demographics (hd_demo_sk);

ALTER TABLE catalog_returns
ADD CONSTRAINT fk_cr_refunded_addr_sk FOREIGN KEY (cr_refunded_addr_sk)
REFERENCES customer_address (ca_address_sk);

ALTER TABLE catalog_returns
ADD CONSTRAINT fk_cr_returning_customer_sk FOREIGN KEY (cr_returning_customer_sk)
REFERENCES customer (c_customer_sk);

ALTER TABLE catalog_returns
ADD CONSTRAINT fk_cr_returning_cdemo_sk FOREIGN KEY (cr_returning_cdemo_sk)
REFERENCES customer_demographics (cd_demo_sk);

ALTER TABLE catalog_returns
ADD CONSTRAINT fk_cr_returning_hdemo_sk FOREIGN KEY (cr_returning_hdemo_sk)
REFERENCES household_demographics (hd_demo_sk);

ALTER TABLE catalog_returns
ADD CONSTRAINT fk_cr_returning_addr_sk FOREIGN KEY (cr_returning_addr_sk)
REFERENCES customer_address (ca_address_sk);

ALTER TABLE catalog_returns
ADD CONSTRAINT fk_cr_call_center_sk FOREIGN KEY (cr_call_center_sk)
REFERENCES call_center (cc_call_center_sk);

ALTER TABLE catalog_returns
ADD CONSTRAINT fk_cr_catalog_page_sk FOREIGN KEY (cr_catalog_page_sk)
REFERENCES catalog_page (cp_catalog_page_sk);

ALTER TABLE catalog_returns
ADD CONSTRAINT fk_cr_ship_mode_sk FOREIGN KEY (cr_ship_mode_sk)
REFERENCES ship_mode (sm_ship_mode_sk);

ALTER TABLE catalog_returns
ADD CONSTRAINT fk_cr_warehouse_sk FOREIGN KEY (cr_warehouse_sk)
REFERENCES warehouse (w_warehouse_sk);

ALTER TABLE catalog_returns
ADD CONSTRAINT fk_cr_reason_sk FOREIGN KEY (cr_reason_sk)
REFERENCES reason (r_reason_sk);

ALTER TABLE web_sales
ADD CONSTRAINT fk_ws_sold_date_sk FOREIGN KEY (ws_sold_date_sk)
REFERENCES date_dim (d_date_sk);

ALTER TABLE web_sales
ADD CONSTRAINT fk_ws_sold_time_sk FOREIGN KEY (ws_sold_time_sk)
REFERENCES time_dim (t_time_sk);

ALTER TABLE web_sales
ADD CONSTRAINT fk_ws_ship_date_sk FOREIGN KEY (ws_ship_date_sk)
REFERENCES date_dim (d_date_sk);

ALTER TABLE web_sales
ADD CONSTRAINT fk_ws_item_sk FOREIGN KEY (ws_item_sk)
REFERENCES item (i_item_sk);

ALTER TABLE web_sales
ADD CONSTRAINT fk_ws_bill_customer_sk FOREIGN KEY (ws_bill_customer_sk)
REFERENCES customer (c_customer_sk);

ALTER TABLE web_sales
ADD CONSTRAINT fk_ws_bill_cdemo_sk FOREIGN KEY (ws_bill_cdemo_sk)
REFERENCES customer_demographics (cd_demo_sk);

ALTER TABLE web_sales
ADD CONSTRAINT fk_ws_bill_hdemo_sk FOREIGN KEY (ws_bill_hdemo_sk)
REFERENCES household_demographics (hd_demo_sk);

ALTER TABLE web_sales
ADD CONSTRAINT fk_ws_bill_addr_sk FOREIGN KEY (ws_bill_addr_sk)
REFERENCES customer_address (ca_address_sk);

ALTER TABLE web_sales
ADD CONSTRAINT fk_ws_ship_customer_sk FOREIGN KEY (ws_ship_customer_sk)
REFERENCES customer (c_customer_sk);

ALTER TABLE web_sales
ADD CONSTRAINT fk_ws_ship_cdemo_sk FOREIGN KEY (ws_ship_cdemo_sk)
REFERENCES customer_demographics (cd_demo_sk);

ALTER TABLE web_sales
ADD CONSTRAINT fk_ws_ship_hdemo_sk FOREIGN KEY (ws_ship_hdemo_sk)
REFERENCES household_demographics (hd_demo_sk);

ALTER TABLE web_sales
ADD CONSTRAINT fk_ws_ship_addr_sk FOREIGN KEY (ws_ship_addr_sk)
REFERENCES customer_address (ca_address_sk);

ALTER TABLE web_sales
ADD CONSTRAINT fk_ws_web_page_sk FOREIGN KEY (ws_web_page_sk)
REFERENCES web_page (wp_web_page_sk);

ALTER TABLE web_sales
ADD CONSTRAINT fk_ws_web_site_sk FOREIGN KEY (ws_web_site_sk)
REFERENCES web_site (web_site_sk);

ALTER TABLE web_sales
ADD CONSTRAINT fk_ws_ship_mode_sk FOREIGN KEY (ws_ship_mode_sk)
REFERENCES ship_mode (sm_ship_mode_sk);

ALTER TABLE web_sales
ADD CONSTRAINT fk_ws_warehouse_sk FOREIGN KEY (ws_warehouse_sk)
REFERENCES warehouse (w_warehouse_sk);

ALTER TABLE web_sales
ADD CONSTRAINT fk_ws_promo_sk FOREIGN KEY (ws_promo_sk)
REFERENCES promotion (p_promo_sk);

ALTER TABLE web_returns
ADD CONSTRAINT fk_wr_returned_date_sk FOREIGN KEY (wr_returned_date_sk)
REFERENCES date_dim (d_date_sk);

ALTER TABLE web_returns
ADD CONSTRAINT fk_wr_returned_time_sk FOREIGN KEY (wr_returned_time_sk)
REFERENCES time_dim (t_time_sk);

ALTER TABLE web_returns
ADD CONSTRAINT fk_wr_item_sk1 FOREIGN KEY (wr_item_sk)
REFERENCES item (i_item_sk);

ALTER TABLE web_returns
ADD CONSTRAINT fk_wr_item_sk2 FOREIGN KEY (wr_order_number, wr_item_sk)
REFERENCES web_sales (ws_order_number, ws_item_sk);

ALTER TABLE web_returns
ADD CONSTRAINT fk_wr_refunded_customer_sk FOREIGN KEY (wr_refunded_customer_sk)
REFERENCES customer (c_customer_sk);

ALTER TABLE web_returns
ADD CONSTRAINT fk_wr_refunded_cdemo_sk FOREIGN KEY (wr_refunded_cdemo_sk)
REFERENCES customer_demographics (cd_demo_sk);

ALTER TABLE web_returns
ADD CONSTRAINT fk_wr_refunded_hdemo_sk FOREIGN KEY (wr_refunded_hdemo_sk)
REFERENCES household_demographics (hd_demo_sk);

ALTER TABLE web_returns
ADD CONSTRAINT fk_wr_refunded_addr_sk FOREIGN KEY (wr_refunded_addr_sk)
REFERENCES customer_address (ca_address_sk);

ALTER TABLE web_returns
ADD CONSTRAINT fk_wr_returning_customer_sk FOREIGN KEY (wr_returning_customer_sk)
REFERENCES customer (c_customer_sk);

ALTER TABLE web_returns
ADD CONSTRAINT fk_wr_returning_cdemo_sk FOREIGN KEY (wr_returning_cdemo_sk)
REFERENCES customer_demographics (cd_demo_sk);

ALTER TABLE web_returns
ADD CONSTRAINT fk_wr_returning_hdemo_sk FOREIGN KEY (wr_returning_hdemo_sk)
REFERENCES household_demographics (hd_demo_sk);

ALTER TABLE web_returns
ADD CONSTRAINT fk_wr_returning_addr_sk FOREIGN KEY (wr_returning_addr_sk)
REFERENCES customer_address (ca_address_sk);

ALTER TABLE web_returns
ADD CONSTRAINT fk_wr_web_page_sk FOREIGN KEY (wr_web_page_sk)
REFERENCES web_page (wp_web_page_sk);

ALTER TABLE inventory
ADD CONSTRAINT fk_inv_date_sk FOREIGN KEY (inv_date_sk)
REFERENCES date_dim (d_date_sk);

ALTER TABLE inventory
ADD CONSTRAINT fk_inv_item_sk FOREIGN KEY (inv_item_sk)
REFERENCES item (i_item_sk);

ALTER TABLE inventory
ADD CONSTRAINT fk_inv_warehouse_sk FOREIGN KEY (inv_warehouse_sk)
REFERENCES warehouse (w_warehouse_sk);

ALTER TABLE store
ADD CONSTRAINT fk_s_closed_date_sk FOREIGN KEY (s_closed_date_sk)
REFERENCES date_dim (d_date_sk);

ALTER TABLE call_center
ADD CONSTRAINT fk_cc_closed_date_sk FOREIGN KEY (cc_closed_date_sk)
REFERENCES date_dim (d_date_sk);

ALTER TABLE call_center
ADD CONSTRAINT fk_cc_open_date_sk FOREIGN KEY (cc_open_date_sk)
REFERENCES date_dim (d_date_sk);

ALTER TABLE catalog_page
ADD CONSTRAINT fk_cp_start_date_sk FOREIGN KEY (cp_start_date_sk)
REFERENCES date_dim (d_date_sk);

ALTER TABLE catalog_page
ADD CONSTRAINT fk_cp_end_date_sk FOREIGN KEY (cp_end_date_sk)
REFERENCES date_dim (d_date_sk);

ALTER TABLE web_site
ADD CONSTRAINT fk_web_open_date_sk FOREIGN KEY (web_open_date_sk)
REFERENCES date_dim (d_date_sk);

ALTER TABLE web_site
ADD CONSTRAINT fk_web_close_date_sk FOREIGN KEY (web_close_date_sk)
REFERENCES date_dim (d_date_sk);

ALTER TABLE web_page
ADD CONSTRAINT fk_wp_creation_date_sk FOREIGN KEY (wp_creation_date_sk)
REFERENCES date_dim (d_date_sk);

ALTER TABLE web_page
ADD CONSTRAINT fk_wp_access_date_sk FOREIGN KEY (wp_access_date_sk)
REFERENCES date_dim (d_date_sk);

ALTER TABLE web_page
ADD CONSTRAINT fk_wp_customer_sk FOREIGN KEY (wp_customer_sk)
REFERENCES customer (c_customer_sk);

ALTER TABLE customer
ADD CONSTRAINT fk_c_current_cdemo_sk FOREIGN KEY (c_current_cdemo_sk)
REFERENCES customer_demographics (cd_demo_sk);

ALTER TABLE customer
ADD CONSTRAINT fk_c_current_hdemo_sk FOREIGN KEY (c_current_hdemo_sk)
REFERENCES household_demographics (hd_demo_sk);

ALTER TABLE customer
ADD CONSTRAINT fk_c_current_addr_sk FOREIGN KEY (c_current_addr_sk)
REFERENCES customer_address (ca_address_sk);

ALTER TABLE customer
ADD CONSTRAINT fk_c_first_shipto_date_sk FOREIGN KEY (c_first_shipto_date_sk)
REFERENCES date_dim (d_date_sk);

ALTER TABLE customer
ADD CONSTRAINT fk_c_first_sales_date_sk FOREIGN KEY (c_first_sales_date_sk)
REFERENCES date_dim (d_date_sk);

ALTER TABLE customer
ADD CONSTRAINT fk_c_last_review_date_sk FOREIGN KEY (c_last_review_date_sk)
REFERENCES date_dim (d_date_sk);

ALTER TABLE household_demographics
ADD CONSTRAINT fk_hd_income_band_sk FOREIGN KEY (hd_income_band_sk)
REFERENCES income_band (ib_income_band_sk);

ALTER TABLE promotion
ADD CONSTRAINT fk_p_start_date_sk FOREIGN KEY (p_start_date_sk)
REFERENCES date_dim (d_date_sk);

ALTER TABLE promotion
ADD CONSTRAINT fk_p_end_date_sk FOREIGN KEY (p_end_date_sk)
REFERENCES date_dim (d_date_sk);

ALTER TABLE promotion
ADD CONSTRAINT fk_p_item_sk FOREIGN KEY (p_item_sk)
REFERENCES item (i_item_sk);
__EOF__
